spring.application.name=resumax

#chat model

#ollama
#spring.ai.ollama.chat.options.model=ministral-3:3b-cloud

#openai
spring.ai.openai.api-key=${openai-api-key}
spring.ai.ollama.chat.options.model=openai/gpt-oss-120b:free
spring.ai.openai.base-url=https://openrouter.ai/api

#embedding model

#Ollama
#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.embedding.options.model=nomic-embed-text:latest

#postgres
spring.datasource.url= ${database_url}
spring.datasource.username= ${database_username}
spring.datasource.password= ${database_password}

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true

#pgvector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
spring.ai.vectorstore.pgvector.max-document-batch-size=1000

#security

jwt.secretkey=${jwt-security-key}