#h2
spring.datasource.url= ${database_url_test}
spring.datasource.username= ${database_username_test}
spring.datasource.password= ${database_password_test}
spring.datasource.driver-class-name = org.h2.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

##openai
#spring.ai.openai.api-key=${openai-api-key}
#spring.ai.ollama.chat.options.model=openai/gpt-oss-120b:free
#spring.ai.openai.base-url=https://openrouter.ai/api
#
##pgvector
#spring.ai.vectorstore.pgvector.initialize-schema=true
#spring.ai.vectorstore.pgvector.index-type=HNSW
#spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
#spring.ai.vectorstore.pgvector.max-document-batch-size=1000